<?php

$ime;
$prezime;
$naslov = "Početna stranica";

$direktorij = getcwd();
$putanja = dirname($_SERVER["REQUEST_URI"]);
include_once "$direktorij/zaglavlje.php";
include_once "$direktorij/skripte/opcenito_funkcije.php";
include_once "$direktorij/klase/konfiguracija.class.php";
include_once "$direktorij/klase/sesija.class.php";

$smarty->display("index.tpl");
$smarty->display("podnozje.tpl");

function korime($ime, $prezime) {
    return strtolower($ime[0] . $prezime);
}

function ime() {
    global $ime;
    return $ime[rand(0, 284)];
}

function prezime() {
    global $prezime;
    return preg_replace("/[^a-zA-Z,Č,Ć,Ž,Đ,Š,š,đ,ž,ć,č]/", "", $prezime[rand(0, 710)]);
}

function mailo($korime) {
    return $korime . "@mail.com";
}

function stvoriKorisnike($direktorij) {
    $baza = new Baza();
    $baza->spojiDB();
    for ($i = 0; $i < 50; $i++) {
        $iime = ime();
        $iprezime = prezime();
        $ime_prezime = $iime . " " . $iprezime;
        $korime = korime($iime, $iprezime);
        $lozinka = $korime . $i;
        $konf = new Konfiguracija($direktorij);
        $datum = $konf->virtualnoVrijeme();
        $aktivacijski_kod = aktivacijskiKod();
        $email = mailo($korime);

        $baza->korisnik_spremi(array("korisnicko_ime" => "$korime", "ime_prezime" => "$ime_prezime", "email" => "$email", "lozinka" => "$lozinka", "datum_vrijeme_registracije" => "$datum", "uvjeti_koristenja" => "$datum", "aktivacijski_kod" => "$aktivacijski_kod"));
    }
    $baza->zatvoriDB();
}

function globaliziraj() {
    global $ime;
    $ime = ['Berislava', 'Blaga', 'Blagica', 'Bogdana', 'Bogomila', 'Bogumila', 'Borka', 'Borislava', 'Božena', 'Božica', 'Božidarka', 'Branimira', 'Branka', 'Buga', 'Cvita', 'Cvijeta', 'Danica', 'Davorka', 'Divna', 'Dragana', 'Dragica', 'Dragomirka', 'Dragomira', 'Draginja', 'Dragina', 'Draga', 'Draženka', 'Dubravka', 'Dunja', 'Hrvoja', 'Hrvojka', 'Jasenka', 'Jasna', 'Ljuba', 'Ljubica', 'Mila', 'Milica', 'Miljenka', 'Mislava', 'Mira', 'Mirjana', 'Mirka', 'Misirka', 'Mirna', 'Mojmira', 'Morana', 'Nada', 'Neda', 'Nediljka', 'Nevenka', 'Ognjenka', 'Ranka', 'Rašeljka', 'Ratka', 'Ruža', 'Ružica', 'Sanja', 'Slava', 'Slavica', 'Slavenka', 'Smiljana', 'Spomenka', 'Srebrenka', 'Stanislava', 'Stana', 'Stanka', 'Snješka', 'Snježana', 'Sunčana', 'Sunčica', 'Tjeha', 'Tihana', 'Tihomila', 'Tuga', 'Vedrana', 'Vera', 'Verica', 'Vjera', 'Vesna', 'Vjekoslava', 'Vlasta', 'Vlatka', 'Zdenka', 'Zlata', 'Zora', 'Zorica', 'Zorka', 'Zrinka', 'Zrina', 'Zvjezdana', 'Zvonimira', 'Zvonka', 'Zeljka', 'ZivkaBerislav', 'Berivoj', 'Blago', 'Bogdan', 'Bogumil', 'Bogoljub', 'Bogomil', 'Bojan', 'Boris', 'Borislav', 'Borna', 'Božetjeh', 'Božidar', 'Božo', 'Bratislav', 'Budimir', 'Branimir', 'Brajko', 'Branko', 'Braslav', 'Bratoljub', 'Cvitko', 'Cvjetko', 'Caslav', 'Castimir', 'Cedomir', 'Dalibor', 'Damir', 'Darko', 'Davor', 'Desimir', 'Dobroslav', 'Dobrovit', 'Domagoj', 'Dragan', 'Drago', 'Dragoslav', 'Dragutin', 'Dragomir', 'Dražen', 'Držiha', 'Držislav', 'Godemir', 'Gojko', 'Gojislav', 'Gojslav', 'Goran', 'Grubiša', 'Hrvatin', 'Hrvoj', 'Hrvoje', 'Hrvoslav', 'Kazimir', 'Kažimir', 'Jasenko', 'Klonimir', 'Krešimir', 'Krševan', 'Lavoslav', 'Ljubomir', 'Ljudevit', 'Milan', 'Mile', 'Milivoj', 'Milovan', 'Miljenko', 'Mirko', 'Miroslav', 'Miroš', 'Mislav', 'Mladen', 'Mojmir', 'Mutimir', 'Nediljko', 'Nedjeljko', 'Nenad', 'Ognjen', 'Ostoja', 'Ozren', 'Predrag', 'Pribislav', 'Prvan', 'Prvoslav', 'Prvoš', 'Radimir', 'Radomir', 'Radoš', 'Rajko', 'Ranko', 'Ratimir', 'Ratko', 'Rato', 'Radovan', 'Radoslav', 'Slaven', 'Slaviša', 'Slavoljub', 'Slavomir', 'Smiljan', 'Spomenko', 'Srebrenko', 'Srećko', 'Stanislav', 'Stanko', 'Strahimir', 'Svetoslav', 'Tihomil', 'Tihomir', 'Tješimir', 'Tomislav', 'Tomo', 'Tvrtko', 'Trpimir', 'Vatroslav', 'Većeslav', 'Vedran', 'Velimir', 'Veselko', 'Vidoslav', 'Vjekoslav', 'Vjenceslav', 'Višeslav', 'Vitomir', 'Vjeran', 'Vladimir', 'Vlado', 'Vlatko', 'Vojmil', 'Vojnomir', 'Vuk', 'Zdenko', 'Zdeslav', 'Zdravko', 'Zorislav', 'Zoran', 'Zrinko', 'Zrinoslav', 'Zlatko', 'Zvonimir', 'Zvonko', 'Zarko', 'Zelimir', 'Zeljko', 'Zivko', 'Aleksandar', 'Ana', 'Ante', 'Andrija', 'Danijel', 'David', 'Dominik', 'Edvard', 'Filip', 'Franjo', 'Fridrik', 'Grgur', 'Henrik', 'Ilija', 'Ivan', 'Jakov', 'Josip', 'Juraj', 'Karlo', 'Katarina', 'Kristofor', 'Lav', 'Ljudevit', 'Lovro', 'Luka', 'Marko', 'Marija', 'Matej', 'Mihael', 'Mihovil', 'Mihajlo', 'Nikola', 'Nikša', 'Niko', 'Mikula', 'Pavao', 'Petar', 'Pero', 'Rikard', 'Sebastijan', 'Silvestar', 'Simun', 'Stjepan', 'Stipan', 'Stipe', 'Toma', 'Vasilije', 'Vilim', 'Vinko'];
    global $prezime;
    $prezime = [
        'Abadžić', 'Abramović
', 'Adamović
', 'Ančić
', 'Andrić
', 'Andrijašević
', 'Androić
', 'Anić
', 'Aničić
', 'Antić
', 'Antolić
', 'Antonić
', 'Antunović
', 'Aračić
', 'Aralica
', 'Arambasić
', 'Arapović
', 'Babić
', 'Bačić
', 'Bagarić
', 'Bajić
', 'Bakarić
', 'Bakić
', 'Baković
', 'Bakula
', 'Balašević
', 'Balić
', 'Banović
', 'Barić
', 'Barišić
', 'Barukčić
', 'Bašić
', 'Batinović
', 'Bebek
', 'Bebić
', 'Begić
', 'Begović
', 'Bekić
', 'Belić
', 'Benčić
', 'Berislavić
', 'Berković
', 'Bilić
', 'Bišćan
', 'Biškup
', 'Biškupić
', 'Blažević
', 'Blažić
', 'Boban
', 'Bobić
', 'Bodrožić
', 'Bodul
', 'Bogdanovich
', 'Bogović
', 'Bojanić
', 'Bojić
', 'Bokun
', 'Bonačić
', 'Borić
', 'Bošković
', 'Bosnić
', 'Bošnjak
', 'Bošnjaković
', 'Božić
', 'Bradarić
', 'Bradić
', 'Brajković
', 'Bratulić
', 'Brdar
', 'Brekalo
', 'Brkić
', 'Broz
', 'Brozović
', 'Bubalo
', 'Budimir
', 'Budiša
', 'Bujas
', 'Bukvić
', 'Bulić
', 'Buljević
', 'Buljubašić
', 'Bunjevčević
', 'Burić
', 'Bušić
', 'Butorac
', 'Čačić
', 'Caktaš
', 'Ćaleta
', 'Čarapić
', 'Čaušić
', 'Ćavar
', 'Černeka
', 'Čilić
', 'Cindrić
', 'Čingrija
', 'Ciprić
', 'Čirjak
', 'Čizmić
', 'Čolić
', 'Čop
', 'Ćopić
', 'Ćorić
', 'Ćorluka
', 'Ćosić
', 'Crijević
', 'Crnčić
', 'Crnković
', 'Čulina
', 'Čulo
', 'Čupić
', 'Ćurković
', 'Cvek
', 'Cvjetićanin
', 'Dadić
', 'Dalić
', 'Damijanić
', 'Damjanić
', 'Damjanović
', 'Dančević
', 'Daničić
', 'Davidović
', 'Dedić
', 'Delić
', 'Demirović
', 'Đerek
', 'Devčić
', 'Dević
', 'Dežić
', 'Diklić
', 'Dinčić
', 'Đaković
', 'Dodig
', 'Dodik
', 'Dominiković
', 'Dončić
', 'Draganja
', 'Dragić
', 'Dragičević
', 'Dragojević
', 'Dragović
', 'Drašković
', 'Dražeta
', 'Drmić
', 'Dudan
', 'Dujmović
', 'Đurić
', 'Džono
', 'Elezović
', 'Eraković
', 'Erceg
', 'Erlić
', 'Fančović
', 'Ferić
', 'Filipović
', 'Forlani
', 'Franić
', 'Franulović
', 'Gabrić
', 'Gaćeša
', 'Gagula
', 'Galić
', 'Galović
', 'Gaši
', 'Gavrilović
', 'Gegić
', 'Glavan
', 'Glavaš
', 'Glavina
', 'Gleđević
', 'Golić
', 'Golubić
', 'Goluža
', 'Gović
', 'Granić
', 'Graovac
', 'Grbić
', 'Grgić
', 'Grgurević
', 'Grubišić
', 'Gudelj
', 'Gutić
', 'Hadžić
', 'Haračić
', 'Harambašić
', 'Haramija
', 'Herceg
', 'Herjavec
', 'Hodak
', 'Horvat
', 'Hrgota
', 'Hrkać
', 'Ignjatić
', 'Ilić
', 'Iličić
', 'Ilijić
', 'Ivančević
', 'Ivančić
', 'Ivanek
', 'Ivanić
', 'Ivanišević
', 'Ivanković
', 'Ivanović
', 'Iveković
', 'Ivić
', 'Ivković
', 'Jagić
', 'Jajalo
', 'Jakovina
', 'Jakovljević
', 'Jakšić
', 'Janić
', 'Janjić
', 'Janković
', 'Japundža
', 'Jedvaj
', 'Jelačić
', 'Jelavić
', 'Jelenić
', 'Jelić
', 'Jeličić
', 'Jerković
', 'Ježić
', 'Ježina
', 'Joković
', 'Jonjić
', 'Josipović
', 'Jovančević
', 'Jović
', 'Jozić
', 'Jugović
', 'Jukić
', 'Juraš
', 'Jurčević
', 'Jurić
', 'Juričić
', 'Jurišić
', 'Jurjević
', 'Jurkovič
', 'Kačić
', 'Kalaus
', 'Kalinić
', 'Kapetanović
', 'Kapić
', 'Kapitanović
', 'Karačić
', 'Karapandža
', 'Kardum
', 'Karić
', 'Karišik
', 'Karlović
', 'Marcelić
', 'Katanić
', 'Katić
', 'Klepač
', 'Klešić
', 'Klisanin
', 'Kljajić
', 'Kljaković
', 'Klobučar
', 'Knežević
', 'Kokić
', 'Kokotović
', 'Kolar
', 'Kolega
', 'Kolesar
', 'Komljenović
', 'Komšić
', 'Korlević
', 'Kos
', 'Kosanović
', 'Kosor
', 'Kostadinović
', 'Kostelić
', 'Kostović
', 'Kotromanović
', 'Kovač
', 'Kovačec
', 'Kovačev
', 'Kovačević
', 'Kovačić
', 'Kožul
', 'Kožulj
', 'Krajinović
', 'Kralj
', 'Kraljević
', 'Kramarić
', 'Kranjčar
', 'Krasić
', 'Krcmar
', 'Kreković
', 'Kresoja
', 'Kristić
', 'Krištić
', 'Križić
', 'Krnčević
', 'Kružić
', 'Kržan
', 'Kučinić
', 'Kujundžić
', 'Kukoč
', 'Kulić
', 'Kuljerić
', 'Kurelac
', 'Kurtović
', 'Kvesić
', 'Kvržić
', 'Lalić
', 'Lambaša
', 'Lasić
', 'Latas
', 'Lenković
', 'Leovac
', 'Lesjak
', 'Lešković
', 'Letica
', 'Lisjak
', 'Livaja
', 'Livaković
', 'Liverić
', 'Ljubičić
', 'Ljubojević
', 'Lončar
', 'Lončarević
', 'Lončarić
', 'Lorković
', 'Lovren
', 'Lovrić
', 'Lovrović
', 'Luburić
', 'Lucić
', 'Lučić
', 'Lukačević
', 'Luketić
', 'Lukić
', 'Lukšić
', 'Lulić
', 'Maček
', 'Maganjić
', 'Maglica
', 'Majer
', 'Majić
', 'Majstorović
', 'Maletić
', 'Maljković
', 'Malkovich
', 'Mamić
', 'Mandić
', 'Mandich
', 'Mandušić
', 'Mandžukić
', 'Marasović
', 'Marčić
', 'Marić
', 'Maričić
', 'Marinković
', 'Marinović
', 'Marjanović
', 'Marković
', 'Marojević
', 'Marotti
', 'Marović
', 'Martić
', 'Martinović
', 'Marušić
', 'Matanović
', 'Matić
', 'Matijević
', 'Matko
', 'Matković
', 'Matoš
', 'Matošević
', 'Matulović
', 'Mažuranić
', 'Mećava
', 'Mešić
', 'Mesić
', 'Meštrović
', 'Mezulić
', 'Mihić
', 'Mijačika
', 'Mijatović
', 'Mikić
', 'Mikšić
', 'Mikulić
', 'Milanović
', 'Milardović
', 'Miletić
', 'Milić
', 'Milićević
', 'Miličević
', 'Miličić
', 'Milinović
', 'Miljković
', 'Milobar
', 'Milošević
', 'Minić
', 'Mirković
', 'Mirović
', 'Mišak
', 'Mišić
', 'Mišković
', 'Mladenović
', 'Mlinarić
', 'Modrić
', 'Mrdeža
', 'Mrkonjić
', 'Mrnavić
', 'Mrsić
', 'Mršić
', 'Mudrinić
', 'Muhić
', 'Muhoberac
', 'Mulić
', 'Musulin
', 'Nadoveza
', 'Nakić
', 'Nazor
', 'Nikić
', 'Nikiš
', 'Nikolić
', 'Ninković
', 'Nišić
', 'Nižić
', 'Njirić
', 'Novak
', 'Novaković
', 'Novosel
', 'Novoselić
', 'Obratov
', 'Ogresta
', 'Ojdanić
', 'Olić
', 'Olujić
', 'Orešković
', 'Orlić
', 'Oršanić
', 'Ostojić
', 'Pačariz
', 'Pandurović
', 'Pašalić
', 'Paunović
', 'Pavelić
', 'Pavić
', 'Pavičić
', 'Pavković
', 'Pavletić
', 'Pavlich
', 'Pavličić
', 'Pavlović
', 'Pejaković
', 'Pejčinović
', 'Pejić
', 'Pera
', 'Perić
', 'Perica
', 'Perišić
', 'Perković
', 'Perošević
', 'Perović
', 'Peruško
', 'Petković
', 'Petrić
', 'Petričević
', 'Petronijević
', 'Petrović
', 'Pijević
', 'Pilipović
', 'Pivarić
', 'Plantak
', 'Pletikosić
', 'Podrug
', 'Pokaz
', 'Polić
', 'Ponoš
', 'Poparić
', 'Popović
', 'Posavec
', 'Požgaj
', 'Pralija
', 'Prelec
', 'Prelog
', 'Primorac
', 'Prkačin
', 'Prpić
', 'Puhovski
', 'Pulisic
', 'Punčec
', 'Pusić
', 'Pušić
', 'Puškarić
', 'Račić
', 'Racki
', 'Računica
', 'Radić
', 'Radman
', 'Radonić
', 'Radonjić
', 'Radoš
', 'Radošević
', 'Radovanović
', 'Rajčić
', 'Rajić
', 'Rakić
', 'Rakitić
', 'Rančić
', 'Rašeta
', 'Rašić
', 'Rastić
', 'Ratković
', 'Ravlić
', 'Rebić
', 'Resetar
', 'Rešetar
', 'Ribar
', 'Rodeš
', 'Rodić
', 'Roglić
', 'Roksandić
', 'Roso
', 'Rozga
', 'Rozić
', 'Rožić
', 'Rudić
', 'Rukavina
', 'Ružić
', 'Sabolić
', 'Sakač
', 'Sakić
', 'Šakić
', 'Šakota
', 'Salopek
', 'Šančić
', 'Šantić
', 'Saračević
', 'Šarčević
', 'Šarić
', 'Šašić
', 'Šegrt
', 'Sekulić
', 'Selak
', 'Šeparović
', 'Šeper
', 'Serdarušić
', 'Sertić
', 'Šešelj
', 'Šikić
', 'Silić
', 'Šiljeg
', 'Šimenc
', 'Simić
', 'Šimić
', 'Šimonović
', 'Simović
', 'Šimun
', 'Šimunić
', 'Šimunović
', 'Sinković
', 'Šipek
', 'Širko
', 'Širola
', 'Skok
', 'Skoko
', 'Škorić
', 'Škoro
', 'Škrlec
', 'Skrmetta
', 'Škugor
', 'Slabinac
', 'Smičiklas
', 'Šoda
', 'Sokač
', 'Sokol
', 'Sokolović
', 'Soldo
', 'Sorkočević
', 'Šovagović
', 'Spajić
', 'Spanić
', 'Špiranović
', 'Špirić
', 'Špoljarić
', 'Sršen
', 'Srzentić
', 'Štampalija
', 'Stanić
', 'Stanich
', 'Stanković
', 'Starčević
', 'Starcevich
', 'Stepinac
', 'Štimac
', 'Stipančević
', 'Stipčević
', 'Stipetić
', 'Glavinić
', 'Stipić
', 'Stjepanović
', 'Stojanović
', 'Stojić
', 'Stošić
', 'Strinić
', 'Stulić
', 'Subašić
', 'Šuker
', 'Šulentić
', 'Sumich
', 'Šunjić
', 'Šupuk
', 'Šuput
', 'Šušak
', 'Šutalo
', 'Suton
', 'Švarc
', 'Šverko
', 'Talajić
', 'Tinjić
', 'Tomas
', 'Tomašević
', 'Tomasović
', 'Tomčić
', 'Tomić
', 'Tomljanović
', 'Tomljenović
', 'Tonković
', 'Tonkovich
', 'Toperić
', 'Topić
', 'Tošić
', 'Trbojević
', 'Trinajstić
', 'Tripković
', 'Tuđman
', 'Turković
', 'Ugrenović
', 'Ujević
', 'Valentić
', 'Varvodić
', 'Veić
', 'Vekić
', 'Veselica
', 'Vidaković
', 'Vidošević
', 'Vidošić
', 'Vidović
', 'Visković
', 'Višković
', 'Višnjić
', 'Vitaić
', 'Vladić
', 'Vladislavić
', 'Vlahov
', 'Vlahović
', 'Vlak
', 'Vlaović
', 'Vlašić
', 'Vlatković
', 'Voinovich
', 'Vorkapić
', 'Vrandečić
', 'Vranić
', 'Vranješ
', 'Vranjković
', 'Vranković
', 'Vrdoljak
', 'Vrhovac
', 'Vrhovec
', 'Vrljić
', 'Vrsaljko
', 'Vučetić
', 'Vučević
', 'Vučković
', 'Vuckovich
', 'Vujčić
', 'Vujević
', 'Vujić
', 'Vujović
', 'Vukas
', 'Vukašinović
', 'Vukasović
', 'Vukčević
', 'Vukelić
', 'Vukić
', 'Vukičević
', 'Vuković
', 'Vuksan
', 'Vuksanović
', 'Vuletić
', 'Vulić
', 'Vulin
', 'Vušković
', 'Yelich
', 'Zadro
', 'Žagar
', 'Zagorac
', 'Zaninović
', 'Zebić
', 'Zec
', 'Zekić
', 'Zelić
', 'Zeljković
', 'Žeravica
', 'Žeželj
', 'Žigić
', 'Žilić
', 'Živković
', 'Živulić
', 'Zlatković
', 'Zorić
', 'Zorko
', 'Zovko
', 'Zrilić
', 'Zrnčić
', 'Zubčić
', 'Župarić
', 'Žuvela'];
}
